const { GraphQLString, GraphQLInt, GraphQLNonNull } = require("graphql");

// Arguments for inserting a customer
const insertCustomerArgs = {
  CustName: { type: new GraphQLNonNull(GraphQLString) },
  CustGender: { type: GraphQLString },
  HouseName: { type: GraphQLString },
  CustAddr1: { type: GraphQLString },
  CustAddr2: { type: GraphQLString },
  LandMark: { type: GraphQLString },
  CustPlace: { type: GraphQLString },
  CustCity: { type: GraphQLString },
  DistrictName: { type: GraphQLString },
  StateName: { type: GraphQLString },
  CountryName: { type: GraphQLString },
  CustPin: { type: GraphQLString },
  CustContPerson: { type: GraphQLString },
  CustContPhone: { type: GraphQLString },
  CustPhone: { type: GraphQLString },
  CustMob: { type: GraphQLString },
  CustEmail: { type: GraphQLString },
  CustFax: { type: GraphQLString },
  CustWebsite: { type: GraphQLString },
  CustRegDate: { type: GraphQLString },
  CustDefltTouch: { type: GraphQLString },
  CardNo: { type: GraphQLString },
  OpeningAmount: { type: GraphQLString },
  Created_by: { type: new GraphQLNonNull(GraphQLString) },
  Last_modified_by: { type: GraphQLString },
  Company_id: { type: new GraphQLNonNull(GraphQLInt) },
  Branch_id: { type: new GraphQLNonNull(GraphQLInt) },
  Counter_id: { type: GraphQLInt },
  IsActive: { type: GraphQLInt },
  TranferStatus: { type: GraphQLString },
  refID: { type: GraphQLInt },
  AreaId: { type: GraphQLInt },
  Panchayathid: { type: GraphQLInt },
  ReligionId: { type: GraphQLInt },
  CustPanNo: { type: GraphQLString },
  CustGstNo: { type: GraphQLString },
  VoucherTypeId: { type: GraphQLInt },
  careof: { type: GraphQLString },
  LedgerCreation: { type: GraphQLString },
  CustAdharno: { type: GraphQLString },
  Relationship: { type: GraphQLString },
  RelationName: { type: GraphQLString },
  PanType: { type: GraphQLString },
};

// Arguments for updating a customer
const updateCustomerArgs = {
  CustId: { type: new GraphQLNonNull(GraphQLInt) },
  CustName: { type: GraphQLString },
  CustGender: { type: GraphQLString },
  HouseName: { type: GraphQLString },
  CustAddr1: { type: GraphQLString },
  CustAddr2: { type: GraphQLString },
  LandMark: { type: GraphQLString },
  CustPlace: { type: GraphQLString },
  CustCity: { type: GraphQLString },
  DistrictName: { type: GraphQLString },
  StateName: { type: GraphQLString },
  CountryName: { type: GraphQLString },
  CustPin: { type: GraphQLString },
  CustContPerson: { type: GraphQLString },
  CustContPhone: { type: GraphQLString },
  CustPhone: { type: GraphQLString },
  CustMob: { type: GraphQLString },
  CustEmail: { type: GraphQLString },
  CustFax: { type: GraphQLString },
  CustWebsite: { type: GraphQLString },
  CustRegDate: { type: GraphQLString },
  CustDefltTouch: { type: GraphQLString },
  CardNo: { type: GraphQLString },
  OpeningAmount: { type: GraphQLString },
  Created_by: { type: GraphQLString },
  Last_modified_by: { type: GraphQLString },
  Company_id: { type: GraphQLInt },
  Branch_id: { type: GraphQLInt },
  Counter_id: { type: GraphQLInt },
  IsActive: { type: GraphQLInt },
  TranferStatus: { type: GraphQLString },
  refID: { type: GraphQLInt },
  AreaId: { type: GraphQLInt },
  Panchayathid: { type: GraphQLInt },
  ReligionId: { type: GraphQLInt },
  CustPanNo: { type: GraphQLString },
  CustGstNo: { type: GraphQLString },
  VoucherTypeId: { type: GraphQLInt },
  careof: { type: GraphQLString },
  LedgerCreation: { type: GraphQLString },
  CustAdharno: { type: GraphQLString },
  Relationship: { type: GraphQLString },
  RelationName: { type: GraphQLString },
  PanType: { type: GraphQLString },
};

// Arguments for deleting a customer
const deleteCustomerArgs = {
  CustId: { type: new GraphQLNonNull(GraphQLInt) },
};

module.exports = {
  insertCustomerArgs,
  updateCustomerArgs,
  deleteCustomerArgs,
};
